version: "3.9"

services: 
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - 8000:80
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
    networks: 
      - app-network
  
  app:
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: app
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 9000:9000
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge